### ISSUE TITLE
No lists appearing in Campaign Monitor List dropdown

### ISSUE THREAD

**Issue by yellostudio** [xportde/campaignmonitor#2]
I have put the API details in but the Campaign Monitor List doesnt show any values. 

Any ideas?

**Comment by Casper-O** [comment]
I guess you already have a list in campaign monitor? If not you should make one.

Else you should check for spaces in front/back of the api keys

**Comment by pgml** [comment]
Just out of curiosity, is it working now?

**Comment by pgml** [comment]
I just assume it's working now.
