### ISSUE TITLE
Fatal Error on install line 403

### ISSUE THREAD

**Issue by Casper-O** [xportde/campaignmonitor#3]
I wanted to install the most recent version on an older 1.6.0.X shop, before I did so I uninstalled the old and i now get the following error when i try to configure the module:

```
Fatal error: Cannot use object of type stdClass as array in /html/prestashop/modules/campaignmonitor/campaignmonitor.php on line 403
[PrestaShop] Fatal error in module campaignmonitor:
Cannot use object of type stdClass as array
```

**Comment by Casper-O** [comment]
I managed to get things working by rewriting this function, as it seems like it would return a object instead of an array in case you have not yet setup the CM api data. Im sure it could be done more pretty but it was what i needed to do, to get it working.

'''
function getWebHooks($object = false)
'''
To check if it was an array it was going to return, else it would return false

**Comment by pgml** [comment]
Thanks for reporting! I have released a new version.
Installation should work fine now.

**Comment by Casper-O** [comment]
It looks like it should, I could test on a clean shop later. At least your solution looks more clean

**Comment by pgml** [comment]
If you already downloaded the new release, please redownload it. There was a tiny addition to the fix I had to make, I also updated the archives in the releases section.
